# Generated by Django 2.0.4 on 2018-08-31 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ready_users', models.ManyToManyField(related_name='_chatroom_ready_users_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=50)),
                ('student_background', models.TextField()),
                ('student_profile', models.TextField()),
                ('student_hints', models.TextField(blank=True)),
                ('teacher_background', models.TextField()),
                ('teacher_objective', models.TextField()),
                ('teacher_hints', models.TextField(blank=True)),
                ('visible_to_players', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_version', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='TFQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Scenario')),
            ],
        ),
    ]
