# Generated by Django 2.0.4 on 2018-04-25 19:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.TextField()),
                ('student_background', models.TextField()),
                ('student_profile', models.TextField()),
                ('student_hints', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('teacher_background', models.TextField()),
                ('teacher_objective', models.TextField()),
                ('teacher_hints', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
