# Generated by Django 2.0.4 on 2018-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='scenario_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='student_hints',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='teacher_hints',
            field=models.TextField(),
        ),
    ]
