# Generated by Django 2.0.4 on 2018-05-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180504_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='student_hints',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='teacher_hints',
            field=models.TextField(blank=True),
        ),
    ]
