# Generated by Django 2.0.4 on 2018-09-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180918_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='name',
            new_name='scenario_name',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='visible_to_players',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True),
        ),
    ]
