# Generated by Django 2.0.4 on 2018-09-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180919_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Scenario'),
        ),
    ]
