# Generated by Django 2.0.4 on 2018-05-07 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180507_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.BooleanField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Scenario')),
            ],
        ),
    ]
