# Generated by Django 2.0.4 on 2018-05-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_tfquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfquestion',
            name='answer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
