# Generated by Django 2.0.4 on 2018-05-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20180507_1421'),
        ('chat', '0007_auto_20180507_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='transcript',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.Transcript'),
        ),
    ]
