# Generated by Django 2.1.4 on 2018-12-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnode',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
