# Generated by Django 2.0.4 on 2018-07-09 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_chatroom_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ready_users',
            field=models.ManyToManyField(related_name='_chatroom_ready_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenario',
            name='previous_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Scenario'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='visible_to_players',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(related_name='_chatroom_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
