# Generated by Django 2.0.4 on 2018-07-09 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20180709_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='previous_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Scenario'),
        ),
    ]
