# Generated by Django 2.1.4 on 2018-12-18 20:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatnode_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('transcript', models.TextField()),
                ('instructions', models.TextField()),
                ('profile', models.TextField()),
                ('feedback', models.TextField()),
                ('chat_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.ChatNode')),
            ],
        ),
        migrations.CreateModel(
            name='TFNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250)),
                ('answer', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True)),
                ('feedback', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='chat.TFNode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='onboardlevel',
            name='tf_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.TFNode'),
        ),
    ]
