# Generated by Django 2.0.4 on 2018-08-07 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20180709_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
