# Generated by Django 2.1.4 on 2018-12-18 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20181218_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
