# Generated by Django 2.0.4 on 2018-09-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20180918_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='previous_version',
            new_name='parent',
        ),
    ]
