# Generated by Django 2.1.4 on 2018-12-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chatroom_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardlevel',
            name='instructions',
        ),
        migrations.AddField(
            model_name='onboardlevel',
            name='instructions_left',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardlevel',
            name='instructions_right',
            field=models.TextField(blank=True),
        ),
    ]
