# Generated by Django 2.1.4 on 2018-12-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20181220_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='onboardlevel',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='onboardlevel',
            name='profile',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='onboardlevel',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatnode',
            name='feedback_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Feedback'),
        ),
    ]
