# Generated by Django 2.1.4 on 2019-01-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20181221_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardlevel',
            name='transcript',
        ),
    ]
