# Generated by Django 2.1.3 on 2018-12-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatnode'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.ChatNode'),
        ),
    ]
