# Generated by Django 2.0.4 on 2018-05-04 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0002_auto_20180503_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='users',
        ),
        migrations.AddField(
            model_name='transcript',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
