# Generated by Django 2.0.4 on 2018-05-07 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0003_auto_20180504_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='user',
        ),
        migrations.AddField(
            model_name='transcript',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
