# Generated by Django 2.0.4 on 2018-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20180507_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='last_line',
            field=models.TextField(default=''),
        ),
    ]
