# Generated by Django 2.0.4 on 2018-05-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatroom_transcript'),
        ('research', '0005_transcript_last_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Scenario'),
        ),
    ]
