# Generated by Django 2.0.4 on 2018-05-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20180507_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='tfanswer',
            name='correct_answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tfanswer',
            name='user_answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tfanswer',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
