# Generated by Django 2.0.4 on 2018-05-07 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20180507_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfanswer',
            name='transcript',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.Transcript'),
        ),
    ]
