# Generated by Django 2.0.4 on 2018-06-01 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_auto_20180523_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfanswer',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
